#!/usr/bin/env bash
# Installs nginx web server 

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'server {
    listen 80;
    location / {
        echo "Hello World!";
    }
}' > /var/www/html/index.nginx-debian.html
service nginx restart
