#!/usr/bin/env bash
# Installs and configures HAproxy on server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*
sudo echo "
frontend lb
	bind *:80
	mode http
	default_backend servers
	
backend servers
	mode http
	balance roundrobin
	server web-01 18.234.106.16:80 check
	server web-02 35.174.185.63:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
